#!/usr/bin/env node

const supportedNodeVersions = "^14.0.0 || ^15.0.0 || ^16.0.0";
const chalk = require('chalk');
const { nodeModuleChecker, detectNvm } = require('./helpers/node');
const execa = require('execa');

if (!nodeModuleChecker(supportedNodeVersions)) {
  console.log(chalk.red(
    'You are using Node ' + process.version + ', but this CLI tool requires Node ' + supportedNodeVersions + '.\nPlease upgrade your Node version.'
  ));

  process.exit(1)
}

const commander = require('commander')

commander
  .version(`starter/cli ${require('../package').version}`)
  .usage('<command> [options]')

commander
  .command('init')
  .action(() => {
    require('./actions/init')()
  });


commander.parse(process.argv)
