name: Theme build check

on:
  pull_request:
    branches: [master]
    tags: ['**']
  push:
    branches: [master]
    tags: ['**']

jobs:
  theme-build:
    name: 'Build source code test | Node ${{ matrix.node-version }} | ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        node-version: [20.X, 19.x, 18.x, 17.x, 16.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - name: Install dependencies
      run: cd ./_dev && npm ci

    - name: Build assets
      run: cd ./_dev && npm run build-ci

